import type { OutputLanguage } from "../../core/config/schema";

export type OutputLabels = {
  docTitle: string;
  tableInfoHeading: string;
  columnsHeading: string;
  metaField: string;
  metaValue: string;
  tablePhysicalName: string;
  tableLogicalName: string;
  schema: string;
  primaryKey: string;
  foreignKeys: string;
  indexes: string;
  none: string;
  physicalName: string;
  logicalName: string;
  type: string;
  required: string;
  defaultValue: string;
  size: string;
  minValue: string;
  maxValue: string;
  unique: string;
  notes: string;
  yes: string;
  no: string;
  generatedNote: string;
  overviewHeading: string;
  tableListHeading: string;
  relationshipsHeading: string;
  warningsHeading: string;
  tableLabel: string;
  descriptionLabel: string;
  dialectLabel: string;
  tablesLabel: string;
  relationshipsLabel: string;
  severity: string;
  code: string;
  target: string;
  message: string;
  fromTable: string;
  fromColumn: string;
  toTable: string;
  toColumn: string;
  constraint: string;
  source: string;
  needsReview: string;
  columnsCount: string;
  rowNo: string;
  backToOverview: string;
  pkMarker: string;
  fkMarker: string;
  erDiagramHeading: string;
  erDiagramSheet: string;
  viewErDiagram: string;
  zoomIn: string;
  zoomOut: string;
  zoomReset: string;
  zoomFit: string;
  panZoomHint: string;
};

const LABELS: Record<OutputLanguage, OutputLabels> = {
  en: {
    docTitle: "Database Documentation",
    tableInfoHeading: "Table Info",
    columnsHeading: "Columns",
    metaField: "Field",
    metaValue: "Value",
    tablePhysicalName: "Table Physical Name",
    tableLogicalName: "Table Logical Name",
    schema: "Schema",
    primaryKey: "Primary Key",
    foreignKeys: "Foreign Keys",
    indexes: "Indexes",
    none: "(none)",
    physicalName: "Physical Name",
    logicalName: "Logical Name",
    type: "Type",
    required: "Required",
    defaultValue: "Default Value",
    size: "Size",
    minValue: "Min",
    maxValue: "Max",
    unique: "Unique",
    notes: "Notes",
    yes: "Yes",
    no: "No",
    generatedNote: "Generated by dbdocgen in A5:SQL-style layout.",
    overviewHeading: "Overview",
    tableListHeading: "Table List",
    relationshipsHeading: "Relationships",
    warningsHeading: "Warnings",
    tableLabel: "Table",
    descriptionLabel: "Description",
    dialectLabel: "Dialect",
    tablesLabel: "Tables",
    relationshipsLabel: "Relationships",
    severity: "Severity",
    code: "Code",
    target: "Target",
    message: "Message",
    fromTable: "From Table",
    fromColumn: "From Column",
    toTable: "To Table",
    toColumn: "To Column",
    constraint: "Constraint",
    source: "Source",
    needsReview: "Needs Review",
    columnsCount: "Columns",
    rowNo: "#",
    backToOverview: "← Overview",
    pkMarker: "PK",
    fkMarker: "FK",
    erDiagramHeading: "ER Diagram",
    erDiagramSheet: "ER Diagram",
    viewErDiagram: "View interactive ER diagram (html/er-diagram.html)",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomReset: "Reset",
    zoomFit: "Fit",
    panZoomHint: "Drag to pan · Scroll to zoom"
  },
  jp: {
    docTitle: "Database Documentation",
    tableInfoHeading: "Table Info",
    columnsHeading: "Columns",
    metaField: "項目",
    metaValue: "値",
    tablePhysicalName: "テーブル物理名",
    tableLogicalName: "テーブル論理名",
    schema: "スキーマ",
    primaryKey: "主キー",
    foreignKeys: "外部キー",
    indexes: "インデックス",
    none: "(none)",
    physicalName: "物理名",
    logicalName: "論理名",
    type: "型",
    required: "必須",
    defaultValue: "デフォルト値",
    size: "桁数",
    minValue: "最小値",
    maxValue: "最大値",
    unique: "一意",
    notes: "備考",
    yes: "Yes",
    no: "No",
    generatedNote: "Generated by dbdocgen in A5:SQL-style layout.",
    overviewHeading: "Overview",
    tableListHeading: "Table List",
    relationshipsHeading: "Relationships",
    warningsHeading: "Warnings",
    tableLabel: "Table",
    descriptionLabel: "Description",
    dialectLabel: "Dialect",
    tablesLabel: "Tables",
    relationshipsLabel: "Relationships",
    severity: "Severity",
    code: "Code",
    target: "Target",
    message: "Message",
    fromTable: "From Table",
    fromColumn: "From Column",
    toTable: "To Table",
    toColumn: "To Column",
    constraint: "Constraint",
    source: "Source",
    needsReview: "Needs Review",
    columnsCount: "列数",
    rowNo: "No.",
    backToOverview: "← 一覧",
    pkMarker: "PK",
    fkMarker: "FK",
    erDiagramHeading: "ER Diagram",
    erDiagramSheet: "ER Diagram",
    viewErDiagram: "インタラクティブER図 (html/er-diagram.html)",
    zoomIn: "拡大",
    zoomOut: "縮小",
    zoomReset: "リセット",
    zoomFit: "全体表示",
    panZoomHint: "ドラッグで移動 · スクロールで拡大縮小"
  }
};

export function getOutputLabels(language: OutputLanguage = "en"): OutputLabels {
  return LABELS[language];
}
