import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { DatabaseDoc, TableDoc } from "../../core/model/database-doc";
import { sanitizeFilename } from "../../core/sanitize";

export type HtmlExportOptions = {
  outDir: string;
};

export async function exportHtmlDocs(
  doc: DatabaseDoc,
  options: HtmlExportOptions,
): Promise<void> {
  try {
    await mkdir(options.outDir, { recursive: true });
    const htmlDir = join(options.outDir, "html");
    const tablesDir = join(htmlDir, "tables");
    await mkdir(tablesDir, { recursive: true });

    await writeFile(
      join(htmlDir, "index.html"),
      renderIndexPage(doc),
      "utf8",
    );

    for (const table of doc.tables) {
      await writeFile(
        join(tablesDir, `${sanitizeFilename(table.name)}.html`),
        renderTablePage(table, doc),
        "utf8",
      );
    }
  } catch (err) {
    throw new Error(
      `Failed to export HTML docs: ${err instanceof Error ? err.message : String(err)}`,
      { cause: err },
    );
  }
}

function pageShell(title: string, body: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${esc(title)} - Database Documentation</title>
  <style>
    :root {
      --bg: #fafbfc;
      --card: #fff;
      --text: #1a1a2e;
      --muted: #6b7280;
      --border: #e5e7eb;
      --accent: #2563eb;
      --code-bg: #f1f5f9;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
      background: var(--bg); color: var(--text); line-height: 1.6;
      max-width: 960px; margin: 0 auto; padding: 2rem 1.5rem;
    }
    h1 { font-size: 1.75rem; margin-bottom: 1rem; }
    h2 { font-size: 1.25rem; margin: 1.5rem 0 0.75rem; border-bottom: 2px solid var(--border); padding-bottom: 0.25rem; }
    table { width: 100%; border-collapse: collapse; margin: 0.75rem 0; background: var(--card); border-radius: 8px; overflow: hidden; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }
    th, td { padding: 0.5rem 0.75rem; text-align: left; border-bottom: 1px solid var(--border); font-size: 0.9rem; }
    th { background: #f8fafc; font-weight: 600; color: var(--muted); text-transform: uppercase; font-size: 0.75rem; letter-spacing: 0.05em; }
    a { color: var(--accent); text-decoration: none; }
    a:hover { text-decoration: underline; }
    ul { list-style: none; padding-left: 0; }
    li { padding: 0.15rem 0; }
    .back-link { display: inline-block; margin-bottom: 1rem; font-size: 0.875rem; }
    .badge { display: inline-block; padding: 0.1rem 0.4rem; border-radius: 4px; font-size: 0.7rem; font-weight: 600; }
    .badge-pk { background: #dbeafe; color: #1e40af; }
    .badge-fk { background: #fef3c7; color: #92400e; }
    .badge-warn { background: #fee2e2; color: #991b1b; }
    .badge-info { background: #e0f2fe; color: #075985; }
    .footer { margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); color: var(--muted); font-size: 0.8rem; }
  </style>
</head>
<body>
${body}
</body>
</html>`;
}

function renderIndexPage(doc: DatabaseDoc): string {
  let tableRows = "";
  for (const table of doc.tables) {
    const desc = esc(table.description?.value ?? table.comment ?? "");
    const filename = sanitizeFilename(table.name);
    tableRows += `      <tr><td><a href="tables/${encodeURIComponent(filename)}.html">${esc(table.name)}</a></td><td>${desc}</td></tr>\n`;
  }

  const body = `
  <h1>Database Documentation</h1>
  <h2>Tables</h2>
  <table>
    <thead><tr><th>Table</th><th>Description</th></tr></thead>
    <tbody>
${tableRows}    </tbody>
  </table>
  <p class="footer">Generated by dbdocgen</p>
`;
  return pageShell("Tables", body);
}

function renderTablePage(table: TableDoc, doc: DatabaseDoc): string {
  const purpose = esc(table.description?.value ?? table.comment ?? "");

  // Columns
  let colRows = "";
  for (const col of table.columns) {
    let badges = "";
    if (col.isPrimaryKey) badges += '<span class="badge badge-pk">PK</span> ';
    if (col.isForeignKey) badges += '<span class="badge badge-fk">FK</span> ';
    colRows += `      <tr><td>${esc(col.name)}</td><td>${esc(col.type)}</td><td>${col.nullable ? "Yes" : "No"}</td><td>${esc(col.defaultValue ?? "-")}</td><td>${badges}</td><td>${esc(col.comment ?? "")}</td></tr>\n`;
  }

  // Primary Keys
  let pkList = "";
  if (table.primaryKeys.length > 0) {
    for (const pk of table.primaryKeys) {
      pkList += `      <li>${esc(pk)}</li>\n`;
    }
  } else {
    pkList = "      <li>(none)</li>\n";
  }

  // Foreign Keys
  let fkList = "";
  if (table.foreignKeys.length > 0) {
    for (const fk of table.foreignKeys) {
      const name = fk.name ? ` (${esc(fk.name)})` : "";
      fkList += `      <li>${fk.columns.join(", ")} → ${esc(fk.referencedTable)}.${fk.referencedColumns.join(", ")}${name}</li>\n`;
    }
  } else {
    fkList = "      <li>(none)</li>\n";
  }

  // Indexes
  const tableIndexes = doc.indexes.filter(
    (idx) => idx.table === table.name,
  );
  const allIndexes = [
    ...table.indexes,
    ...tableIndexes.filter(
      (idx) => !table.indexes.some((ti) => ti.name === idx.name),
    ),
  ];
  let idxList = "";
  if (allIndexes.length > 0) {
    for (const idx of allIndexes) {
      const unique = idx.unique ? " UNIQUE" : "";
      idxList += `      <li>${esc(idx.name)} on (${idx.columns.join(", ")})${unique}</li>\n`;
    }
  } else {
    idxList = "      <li>(none)</li>\n";
  }

  // Relationships
  const tableRels = doc.relationships.filter(
    (rel) => rel.fromTable === table.name || rel.toTable === table.name,
  );
  let relList = "";
  if (tableRels.length > 0) {
    for (const rel of tableRels) {
      const direction =
        rel.fromTable === table.name
          ? `${esc(rel.fromColumn)} → ${esc(rel.toTable)}.${esc(rel.toColumn)}`
          : `${esc(rel.fromTable)}.${esc(rel.fromColumn)} → ${esc(rel.toColumn)}`;
      const review = rel.needsReview
        ? ' <span class="badge badge-warn">needs review</span>'
        : "";
      relList += `      <li>${direction}${review}</li>\n`;
    }
  } else {
    relList = "      <li>(none)</li>\n";
  }

  // Review TODOs
  let todoList = "";
  if (table.reviewTodos.length > 0) {
    for (const todo of table.reviewTodos) {
      const sug = todo.suggestion ? ` — ${esc(todo.suggestion)}` : "";
      todoList += `      <li>[${esc(todo.type)}] ${esc(todo.target)}: ${esc(todo.issue)}${sug}</li>\n`;
    }
  } else {
    todoList = "      <li>(none)</li>\n";
  }

  const body = `
  <a class="back-link" href="../index.html">← Back to Tables</a>
  <h1>${esc(table.name)}</h1>
  ${purpose ? `<p><strong>Purpose:</strong> ${purpose}</p>` : ""}
  ${table.comment ? `<p><strong>DB Comment:</strong> ${esc(table.comment)}</p>` : ""}

  <h2>Columns</h2>
  <table>
    <thead><tr><th>Name</th><th>Type</th><th>Nullable</th><th>Default</th><th>Keys</th><th>Comment</th></tr></thead>
    <tbody>
${colRows}    </tbody>
  </table>

  <h2>Primary Key</h2>
  <ul>
${pkList}  </ul>

  <h2>Foreign Keys</h2>
  <ul>
${fkList}  </ul>

  <h2>Indexes</h2>
  <ul>
${idxList}  </ul>

  <h2>Relationships</h2>
  <ul>
${relList}  </ul>

  <h2>Review TODOs</h2>
  <ul>
${todoList}  </ul>
`;
  return pageShell(table.name, body);
}

function esc(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}
