import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { DatabaseDoc, TableDoc } from "../../core/model/database-doc";
import { sanitizeFilename } from "../../core/sanitize";

export type MarkdownExportOptions = {
  outDir: string;
};

export async function exportMarkdownDocs(
  doc: DatabaseDoc,
  options: MarkdownExportOptions
): Promise<void> {
  try {
    await mkdir(options.outDir, { recursive: true });
    const tablesDir = join(options.outDir, "tables");
    await mkdir(tablesDir, { recursive: true });

    await writeFile(
      join(options.outDir, "DATABASE.md"),
      renderOverview(doc),
      "utf8"
    );

    for (const table of doc.tables) {
      await writeFile(
        join(tablesDir, `${sanitizeFilename(table.name)}.md`),
        renderTableDoc(table, doc),
        "utf8"
      );
    }
  } catch (err) {
    throw new Error(
      `Failed to export Markdown docs: ${err instanceof Error ? err.message : String(err)}`,
      { cause: err }
    );
  }
}

function renderOverview(doc: DatabaseDoc): string {
  const lines: string[] = [];
  lines.push("# Database Documentation");
  lines.push("");
  lines.push("## Tables");
  lines.push("");
  lines.push("| Table | Description |");
  lines.push("|-------|-------------|");

  for (const table of doc.tables) {
    const desc = table.description?.value ?? table.comment ?? "";
    lines.push(`| ${table.name} | ${escapeMd(desc)} |`);
  }

  lines.push("");

  // Warnings
  lines.push("## Warnings");
  lines.push("");
  if (doc.warnings.length > 0) {
    for (const warning of doc.warnings) {
      const target = warning.target ? ` (${escapeMd(warning.target)})` : "";
      lines.push(
        `- [${escapeMd(warning.severity)}] ${escapeMd(warning.code)}${target}: ${escapeMd(warning.message)}`
      );
    }
  } else {
    lines.push("- (none)");
  }
  lines.push("");

  lines.push("---");
  lines.push("Generated by dbdocgen");
  lines.push("");
  return lines.join("\n");
}

function renderTableDoc(table: TableDoc, doc: DatabaseDoc): string {
  const lines: string[] = [];
  const purpose = table.description?.value ?? table.comment ?? "";

  lines.push(`# ${table.name}`);
  lines.push("");

  if (purpose) {
    lines.push(`**Purpose:** ${escapeMd(purpose)}`);
  }
  if (table.comment) {
    lines.push(`**DB Comment:** ${escapeMd(table.comment)}`);
  }
  lines.push("");

  // Columns
  lines.push("## Columns");
  lines.push("");
  lines.push("| Name | Type | Nullable | Default | PK | FK | Comment |");
  lines.push("|------|------|----------|---------|----|----|---------|");

  for (const col of table.columns) {
    lines.push(
      `| ${escapeMd(col.name)} | ${escapeMd(col.type)} | ${col.nullable ? "Yes" : "No"} | ${escapeMd(col.defaultValue ?? "-")} | ${col.isPrimaryKey ? "Yes" : "No"} | ${col.isForeignKey ? "Yes" : "No"} | ${escapeMd(col.comment ?? "")} |`
    );
  }
  lines.push("");

  // Primary Key
  lines.push("## Primary Key");
  lines.push("");
  if (table.primaryKeys.length > 0) {
    for (const pk of table.primaryKeys) {
      lines.push(`- ${escapeMd(pk)}`);
    }
  } else {
    lines.push("- (none)");
  }
  lines.push("");

  // Foreign Keys
  lines.push("## Foreign Keys");
  lines.push("");
  if (table.foreignKeys.length > 0) {
    for (const fk of table.foreignKeys) {
      const name = fk.name ? ` (${escapeMd(fk.name)})` : "";
      lines.push(
        `- ${fk.columns.join(", ")} → ${escapeMd(fk.referencedTable)}.${fk.referencedColumns.join(", ")}${name}`
      );
    }
  } else {
    lines.push("- (none)");
  }
  lines.push("");

  // Indexes
  lines.push("## Indexes");
  lines.push("");
  const tableIndexes = doc.indexes.filter((idx) => idx.table === table.name);
  const allIndexes = [
    ...table.indexes,
    ...tableIndexes.filter(
      (idx) => !table.indexes.some((ti) => ti.name === idx.name)
    )
  ];

  if (allIndexes.length > 0) {
    for (const idx of allIndexes) {
      const unique = idx.unique ? " UNIQUE" : "";
      lines.push(
        `- ${escapeMd(idx.name)} on (${idx.columns.join(", ")})${unique}`
      );
    }
  } else {
    lines.push("- (none)");
  }
  lines.push("");

  // Relationships
  lines.push("## Relationships");
  lines.push("");
  const tableRels = doc.relationships.filter(
    (rel) => rel.fromTable === table.name || rel.toTable === table.name
  );
  if (tableRels.length > 0) {
    for (const rel of tableRels) {
      const direction =
        rel.fromTable === table.name
          ? `${rel.fromColumn} → ${escapeMd(rel.toTable)}.${rel.toColumn}`
          : `${escapeMd(rel.fromTable)}.${rel.fromColumn} → ${rel.toColumn}`;
      const review = rel.needsReview ? " ⚠ needs review" : "";
      lines.push(`- ${direction}${review}`);
    }
  } else {
    lines.push("- (none)");
  }
  lines.push("");

  // Review TODOs
  lines.push("## Review TODOs");
  lines.push("");
  if (table.reviewTodos.length > 0) {
    for (const todo of table.reviewTodos) {
      const sug = todo.suggestion ? ` — ${escapeMd(todo.suggestion)}` : "";
      lines.push(
        `- [${escapeMd(todo.type)}] ${escapeMd(todo.target)}: ${escapeMd(todo.issue)}${sug}`
      );
    }
  } else {
    lines.push("- (none)");
  }
  lines.push("");

  return lines.join("\n");
}

function escapeMd(text: string): string {
  return text.replace(/([|*_`\[\]<>#~\\])/g, "\\$1");
}
